### ISSUE TITLE
The dependency `go@1.19` doesn't exist

### ISSUE THREAD

**Issue by g-a-c** [k0sproject/homebrew-tap#15]
Version `1.19` of `go` in Homebrew is the _current_ version, so it doesn't have a version suffix; it is simply known as `go` and not `go@1.19` until `1.20` is released. This means that an installed version of `k0sctl` won't upgrade:

```
==> Updated Homebrew from 6e2b162c4 to 427f6465e.
Updated 3 taps (k0sproject/tap, homebrew/bundle and homebrew/services).
==> Outdated Formulae
k0sctl

You have 1 outdated formula installed.
You can upgrade it with brew upgrade
or list it with brew outdated.

==> Upgrading 1 outdated package:
k0sproject/tap/k0sctl 0.13.2 -> 0.14.0
Error: No available formula with the name "go@1.19" (dependency of k0sproject/tap/k0sctl).
```

**Comment by kke** [comment]
That's strange, the brew audit didn't complain at all, I think I even saw it download the go 1.19 bottle. Does an older go like 1.16 pass as "go" or does no suffix always mean "latest"?

**Comment by g-a-c** [comment]
> That's strange, the brew audit didn't complain at all, I think I even saw it download the go 1.19 bottle. Does an older go like 1.16 pass as "go" or does no suffix always mean "latest"?

For the `go` packages, they're usually kept very closely up to date with upstream so no suffix would mean `latest`.

Homebrew is a simpler package manager, there is no equivalent to something like the [DEB format `Provides`](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-virtual). So to the best of my knowledge `go@1.16` will _not_ satisfy a dependency on `go`, nor will `go` satisfy a dependency on `go@1.19`.

**Comment by g-a-c** [comment]
Ohhh, interesting...I think I may have found the issue, and it might not be in this repo after all.

The Homebrew project _does_ have an Alias declared, which effectively means `go@1.19 -> go`. However since the recent Homebrew release, I switched to using their recommended API installation method which doesn't have a local checkout of the Homebrew repository anymore, and it looks like that Alias is not present in the API. I'll take a look more into it, but perhaps there's nothing to "fix" here, as the issue may be coming from Homebrew itself.

**Comment by g-a-c** [comment]
I opened Homebrew/brew#13856 to raise this with the Homebrew project - the fix could be on that side and not in this tap.

**Comment by kke** [comment]
There's nothing that would actually require go1.19, I think there are some things that do require 1.18. Anyway, it's a build dependency, this should only matter if someone is installing `--HEAD` or forcing a build for some other reason.

**Comment by g-a-c** [comment]
I thought that was weird too, but I think that might be another bug in Homebrew; perhaps all dependencies of a formula are evaluated first regardless of how you're attempting to install it, even though some of those dependencies may be "pruned" later in the process.
